# AUTONA - UI automation server (Python 3)
# Copyright (C) 2021 Marco Alvarado
# Visit http://qaware.org

import autopy

languageButtons = {
    'btn_izq': autopy.mouse.Button.LEFT,
    'boton_izquierdo': autopy.mouse.Button.LEFT,
    'btn_med': autopy.mouse.Button.MIDDLE,
    'boton_medio': autopy.mouse.Button.MIDDLE,
    'btn_der': autopy.mouse.Button.RIGHT,
    'boton_derecho': autopy.mouse.Button.RIGHT,
    }

languageKeys = {
    'esc': autopy.key.Code.ESCAPE,
    'escapa': autopy.key.Code.ESCAPE,
    'f1': autopy.key.Code.F1,
    'f2': autopy.key.Code.F2,
    'f3': autopy.key.Code.F3,
    'f4': autopy.key.Code.F4,
    'f5': autopy.key.Code.F5,
    'f6': autopy.key.Code.F6,
    'f7': autopy.key.Code.F7,
    'f8': autopy.key.Code.F8,
    'f9': autopy.key.Code.F9,
    'f10': autopy.key.Code.F10,
    'f11': autopy.key.Code.F11,
    'f12': autopy.key.Code.F12,
    'f13': autopy.key.Code.F13,
    'f14': autopy.key.Code.F14,
    'f15': autopy.key.Code.F15,
    'f16': autopy.key.Code.F16,
    'f17': autopy.key.Code.F17,
    'f18': autopy.key.Code.F18,
    'f19': autopy.key.Code.F19,
    'f20': autopy.key.Code.F20,
    'f21': autopy.key.Code.F21,
    'f22': autopy.key.Code.F22,
    'f23': autopy.key.Code.F23,
    'f24': autopy.key.Code.F24,
    'supr': autopy.key.Code.DELETE,
    'suprime': autopy.key.Code.DELETE,
    'atras': autopy.key.Code.BACKSPACE,
    'tab': autopy.key.Code.TAB,
    'tabula': autopy.key.Code.TAB,
    'retorna': autopy.key.Code.RETURN,
    'intro': autopy.key.Code.RETURN,
    'introduce': autopy.key.Code.RETURN,
    'bloq_mayus': autopy.key.Code.CAPS_LOCK,
    'bloquea_mayusculas': autopy.key.Code.CAPS_LOCK,
    'mayus': autopy.key.Code.SHIFT,
    'mayuscula': autopy.key.Code.SHIFT,
    'mayus_izq': autopy.key.Code.SHIFT,
    'mayuscula_izquierda': autopy.key.Code.SHIFT,
    'mayus_der': autopy.key.Code.SHIFT,
    'mayuscula_derecha': autopy.key.Code.SHIFT,
    'ctrl': autopy.key.Code.CONTROL,
    'control': autopy.key.Code.CONTROL,
    'ctrl_izq': autopy.key.Code.CONTROL,
    'control_izquierdo': autopy.key.Code.CONTROL,
    'ctrl_der': autopy.key.Code.CONTROL,
    'control_derecho': autopy.key.Code.CONTROL,
    'alt': autopy.key.Code.ALT,
    'alterna': autopy.key.Code.ALT,
    'alt_izq': autopy.key.Code.ALT,
    'alterna_izquierda': autopy.key.Code.ALT,
    'alt_der': autopy.key.Code.ALT,
    'alterna_derecha': autopy.key.Code.ALT,
    'cmd': autopy.key.Code.META,
    'comando': autopy.key.Code.META,
    'cmd_izq': autopy.key.Code.META,
    'comando_izquierdo': autopy.key.Code.META,
    'cmd_der': autopy.key.Code.META,
    'comando_derecho': autopy.key.Code.META,
    'esp': autopy.key.Code.SPACE,
    'espacio': autopy.key.Code.SPACE,
    'izq': autopy.key.Code.LEFT_ARROW,
    'izquierda': autopy.key.Code.LEFT_ARROW,
    'der': autopy.key.Code.RIGHT_ARROW,
    'derecha': autopy.key.Code.RIGHT_ARROW,
    'arriba': autopy.key.Code.UP_ARROW,
    'abajo': autopy.key.Code.DOWN_ARROW,
    'inicio': autopy.key.Code.HOME,
    'fin': autopy.key.Code.END,
    're_pag': autopy.key.Code.PAGE_UP,
    'regresa_pagina': autopy.key.Code.PAGE_UP,
    'av_pag': autopy.key.Code.PAGE_DOWN,
    'avanza_pagina': autopy.key.Code.PAGE_DOWN,
    }

languageModifierKeys = {
    'mayus': autopy.key.Modifier.SHIFT,
    'ctrl': autopy.key.Modifier.CONTROL,
    'cmd': autopy.key.Modifier.META,
    'alt': autopy.key.Modifier.ALT,
    }