# AUTONA - UI automation server (Python 3)
# Copyright (C) 2021 Marco Alvarado
# Visit http://qaware.org

import autopy



class Language:
    
    buttons = {
        'clk_lft': autopy.mouse.Button.LEFT,
        'click_left': autopy.mouse.Button.LEFT,
        'clk_mid': autopy.mouse.Button.MIDDLE,
        'click_middle': autopy.mouse.Button.MIDDLE,
        'clk_rgt': autopy.mouse.Button.RIGHT,
        'click_right': autopy.mouse.Button.RIGHT,
        }
    keys = {
        'esc': autopy.key.Code.ESCAPE,
        'escape': autopy.key.Code.ESCAPE,
        'f1': autopy.key.Code.F1,
        'f2': autopy.key.Code.F2,
        'f3': autopy.key.Code.F3,
        'f4': autopy.key.Code.F4,
        'f5': autopy.key.Code.F5,
        'f6': autopy.key.Code.F6,
        'f7': autopy.key.Code.F7,
        'f8': autopy.key.Code.F8,
        'f9': autopy.key.Code.F9,
        'f10': autopy.key.Code.F10,
        'f11': autopy.key.Code.F11,
        'f12': autopy.key.Code.F12,
        'f13': autopy.key.Code.F13,
        'f14': autopy.key.Code.F14,
        'f15': autopy.key.Code.F15,
        'f16': autopy.key.Code.F16,
        'f17': autopy.key.Code.F17,
        'f18': autopy.key.Code.F18,
        'f19': autopy.key.Code.F19,
        'f20': autopy.key.Code.F20,
        'f21': autopy.key.Code.F21,
        'f22': autopy.key.Code.F22,
        'f23': autopy.key.Code.F23,
        'f24': autopy.key.Code.F24,
        'del': autopy.key.Code.DELETE,
        'delete': autopy.key.Code.DELETE,
        'bs': autopy.key.Code.BACKSPACE,
        'backspace': autopy.key.Code.BACKSPACE,
        'tab': autopy.key.Code.TAB,
        'tabulator': autopy.key.Code.TAB,
        'return': autopy.key.Code.RETURN,
        'enter': autopy.key.Code.RETURN,
        'caps_lock': autopy.key.Code.CAPS_LOCK,
        'capitals_lock': autopy.key.Code.CAPS_LOCK,
        'shift': autopy.key.Code.SHIFT,
        'lft_shift': autopy.key.Code.SHIFT,
        'left_shift': autopy.key.Code.SHIFT,
        'rgt_shift': autopy.key.Code.SHIFT,
        'right_shift': autopy.key.Code.SHIFT,
        'ctrl': autopy.key.Code.CONTROL,
        'lft_ctrl': autopy.key.Code.CONTROL,
        'left_ctrl': autopy.key.Code.CONTROL,
        'rgt_ctrl': autopy.key.Code.CONTROL,
        'right_ctrl': autopy.key.Code.CONTROL,
        'alt': autopy.key.Code.ALT,
        'lft_alt': autopy.key.Code.ALT,
        'left_alt': autopy.key.Code.ALT,
        'rgt_alt': autopy.key.Code.ALT,
        'right_alt': autopy.key.Code.ALT,
        'cmd': autopy.key.Code.META,
        'lft_cmd': autopy.key.Code.META,
        'left_cmd': autopy.key.Code.META,
        'rgt_cmd': autopy.key.Code.META,
        'right_cmd': autopy.key.Code.META,
        'space': autopy.key.Code.SPACE,
        'left': autopy.key.Code.LEFT_ARROW,
        'right': autopy.key.Code.RIGHT_ARROW,
        'up': autopy.key.Code.UP_ARROW,
        'down': autopy.key.Code.DOWN_ARROW,
        'home': autopy.key.Code.HOME,
        'end': autopy.key.Code.END,
        'pg_up': autopy.key.Code.PAGE_UP,
        'page_up': autopy.key.Code.PAGE_UP,
        'pg_down': autopy.key.Code.PAGE_DOWN,
        'page_down': autopy.key.Code.PAGE_DOWN,
        }
    modifierKeys = {
        'shift': autopy.key.Modifier.SHIFT,
        'ctrl': autopy.key.Modifier.CONTROL,
        'cmd': autopy.key.Modifier.META,
        'alt': autopy.key.Modifier.ALT,
        }